LINQ_Ejemplo/Controllers/InicioController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using LINQ_Ejemplo.Models;

namespace LINQ_Ejemplo.Controllers
{
    public class InicioController : Controller
    {
        private readonly OperacionDataContext _context;

        public InicioController()
        {
            //Se inicia el modulo LINQ en modo solo lectura para recuperar los datos
            _context = new OperacionDataContext();
        }

        public ActionResult Index()
        {
            //Consulta SQL de mas de una tabla
            IList<DetalleLibro> detalleLista = new List<DetalleLibro>(); // se especifica el modelo de datos
            var query = from li in _context.libros
                join te in _context.tematicas on li.codtema equals te.codtema
                join edit in _context.editoriales on li.codeditorial equals edit.codeditorial
                join idi in _context.idiomas on li.codidioma equals idi.codidioma
                select new
                {
                    Codigo = li.codlibro,
                    Titulo = li.titulo,
                    Tema = te.tema,
                    Editorial = edit.editorial,
                    Idioma = idi.idioma,
                    Precio = li.precio,
                    year = li.year
                };
            //Consulta SQL: 
            //select 
            //li.codlibro,li.titulo,te.tema,edit.editorial,idi.idioma,li.precio,li.year
            //    from libros li
            //inner join tematicas te on li.codtema = te.codtema
            //inner join editoriales edit on li.codeditorial = edit.codeditorial
            //inner join idiomas idi on li.codidioma = idi.codidioma
            var detalles = query.ToList();
            foreach (var detalleData in detalles)
            {
                detalleLista.Add(new DetalleLibro()
                {
                    Codlibro = detalleData.Codigo,
                    Titulo = detalleData.Titulo,
                    Tema = detalleData.Tema,
                    Editorial = detalleData.Editorial,
                    Idioma = detalleData.Idioma,
                    Precio = float.Parse(detalleData.Precio.ToString()),
                    Year = detalleData.year.GetValueOrDefault()
                });
            }
            //luego cargamos los valores dentro del modelo de datos y lo enviamos
            return View(detalleLista);
        }

        public ActionResult Alumno()
        {
            var lista = DdlAlumnos();
            var list = new SelectList(lista, "codigo", "nombre");
            ViewData["alumnos"] = list;
            ViewData["autorizar"] = null;
            return View();
        }

        [HttpPost]
        public ActionResult Alumno(string seleccion)
        {
            //Comando where
            var idi = seleccion;
            var lista = DdlAlumnos();
            var list = new SelectList(lista, "codigo", "nombre");
            ViewData["alumnos"] = list;
            IList<LibrosAlumno> detalleLista = new List<LibrosAlumno>();
            var query = from alum in _context.alumnos
                join pre in _context.prestamos on alum.codalumno equals pre.codalumno
                join ejem in _context.ejemplares on pre.codejemplar equals ejem.codejemplar
                join lib in _context.libros on ejem.codlibro equals lib.codlibro
                where alum.codalumno == seleccion
                select new
                {
                    Nombre = alum.nombre,
                    Fecha = pre.fechaprestamo,
                    Libro = lib.titulo
                };
            //select alum.nombre, pre.fechaprestamo, lib.titulo from alumnos alum
            //inner join prestamos pre on alum.codalumno = pre.codalumno
            //inner join ejemplares ejem on ejem.codejemplar = pre.codejemplar
            //inner join libros lib on lib.codlibro = ejem.codlibro 
            //where alum.codalumno = '122311'
            var listado = query.ToList();
            foreach (var listaEstudiante in listado)
            {
                detalleLista.Add(new LibrosAlumno()
                {
                   Nombre = listaEstudiante.Nombre,
                   Fecha = listaEstudiante.Fecha.ToString(),
                   Titulo = listaEstudiante.Libro
                    
                });
            }
            ViewData["autorizar"] = "entrar";
            return View(detalleLista);
        }

        private List<LibrosAlumno> DdlAlumnos()
        {
            var alumnosDdl = new List<LibrosAlumno>();
            var query = from alum in _context.alumnos
                select new
                {
                    Nombre = alum.nombre,
                    Codigo = alum.codalumno
                };
            //Consulta SQL:
            //select nombre,codalumno from alumnos;
            var lista = query.ToList();
            foreach (var ddlLista in lista)
            {
                alumnosDdl.Add(new LibrosAlumno()
                {
                    Codigo = ddlLista.Codigo,
                    Nombre = ddlLista.Nombre
                });
            }
            return alumnosDdl;
        }

        public ActionResult InsertarLibro()
        {
            libros modelo = new libros();
            //
            var tema = new List<tematicas>();
            var query = from tem in _context.tematicas
                select new
                {
                    codigo = tem.codtema,
                    tematica = tem.tema
                };
            //select codtema,tema from tematicas;
            var lista = query.ToList();
            foreach (var ddltematica in lista)
            {
                tema.Add(new tematicas()
                {
                    codtema = ddltematica.codigo,
                    tema = ddltematica.tematica
                });
            }
            ViewBag.tema = tema;
            //
            var edito = new List<editoriales>();
            var query2 = from edit in _context.editoriales
                select new
                {
                    codigoedito = edit.codeditorial,
                    editorialnombre = edit.editorial
                };
            var lista2 = query2.ToList();
            foreach (var ddleditorial in lista2)
            {
                edito.Add(new editoriales()
                {
                    codeditorial = ddleditorial.codigoedito,
                    editorial = ddleditorial.editorialnombre
                });
            }
            ViewBag.edito = edito;
            //
            var idioma = new List<idiomas>();
            var query3 = from idio in _context.idiomas
                select new
                {
                    idiomacod = idio.codidioma,
                    idiomanombre = idio.idioma
                };
            var lista3 = query3.ToList();
            foreach (var ddlidioma in lista3)
            {
                idioma.Add(new idiomas()
                {
                   codidioma = ddlidioma.idiomacod,
                   idioma = ddlidioma.idiomanombre
                });
            }
            ViewBag.idioma = idioma;
            //
            var autor = new List<autores>();
            var query4 = from aut in _context.autores
                select new
                {
                    autorCod = aut.codautor,
                    autorNombre = aut.autor
                };
            var lista4 = query4.ToList();
            foreach (var ddlautor in lista4)
            {
                autor.Add(new autores()
                {
                    codautor = ddlautor.autorCod,
                    autor = ddlautor.autorNombre
                });
            }
            ViewBag.autor = autor;
            //
            ViewData["regresar"] = "nada";
            return View(modelo);
        }

        [HttpPost]
        public ActionResult InsertarLibro (int donado, libros datos)
        {
            char[] don = new char[5];
            if (donado == 1)
            {
                don[1] = 'S';
            }
            else
            {
                don[1] = 'N';
            }
            int autor = datos.codlibro;
            using (OperacionDataContext objDataContext = new OperacionDataContext())
            {
                datos.donado = don[1];
                try
                {
                    //Comando Insert
                    objDataContext.libros.InsertOnSubmit(datos);
                    objDataContext.SubmitChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
                //
                var libronuevo = new List<libros>();
                var query = from lib in _context.libros
                            where lib.titulo == datos.titulo
                    select new
                    {
                        cod = lib.codlibro
                    };
                var lista = query.ToList();
                int[] codigo = new int[10];
                foreach (var libro in lista)
                {
                    codigo[0] = libro.cod;
                }
                try
                {
                    //Se ejecuta el procedimiento almacenado
                  var queryproc = objDataContext.insertarAutorxLibro(codigo[0], autor);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
                ViewData["regresar"] = "index";
            }
            return View();
        }

        public ActionResult VerAlumnos()
        {
            IList<alumnos> listaAlumnos = new List<alumnos>();
            var query = from alum in _context.alumnos
                select new
                {

LINQ_Ejemplo/Views/Inicio/Alumno.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.LibrosAlumno>
@{
    ViewBag.Title = "Prestamos por alumno";
}
<h2>Comando Where</h2>

@using (Html.BeginForm("Alumno", "Inicio", FormMethod.Post, new { @class = "form-group" }))
{ 

        <div class="input-group mb-3">
            @Html.DropDownList("seleccion", ViewData["alumnos"] as SelectList, new { @class = "form-control" })
            <div class="input-group-append">
                <span>&nbsp;</span>
                <span>&nbsp;</span>
                <button type="submit" value="submit" class="btn btn-outline-primary">Buscar</button>
            </div>
                <br />
            <br />
        </div>

}
@if (ViewData["autorizar"] != null)
{
    <table class="table table-striped table-dark table-responsive-sm table-responsive-md">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Titulo)
                </td>
            </tr>
        }
    </table>
}

LINQ_Ejemplo/Views/Inicio/ArregloNumeros.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.numeros>  
@{
    ViewBag.Title = "Arreglo Numeros";
}

<h2>Arreglo con Numeros</h2>
<table class="table table-striped table-dark table-responsive-sm table-responsive-md align-content-center">
    <tr class="align-content-center">
        <th>
            @Html.DisplayNameFor(model => model.num)
        </th>
    </tr>

    @foreach (var item in Model)
{
    <tr class="align-content-center">
        <td>
            @Html.DisplayFor(model => item.num)
        </td>
    </tr>
}
</table>

LINQ_Ejemplo/Views/Inicio/Autores.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.VistaxAutores>
@{
    ViewBag.Title = "Autores";
}

<h2>Uso de vistas</h2>

<table class="table table-striped table-dark table-responsive-sm table-responsive-md">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.titulo)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.autor)
            </td>
            <td>
                @Html.DisplayFor(model => item.titulo)
            </td>
        </tr>
    }
</table>

LINQ_Ejemplo/Views/Inicio/HistorialPrestamos.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.Historial>
@{
    ViewBag.Title = "Historial Prestamos";
}

<h2>Funciones de agregado</h2>
<table class="table table-striped table-dark table-responsive-sm table-responsive-md">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prestamos)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(model => item.prestamos)
            </td>
        </tr>
    }
</table>

LINQ_Ejemplo/Views/Inicio/Index.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.DetalleLibro>
@{
    ViewBag.Title = "Detalle Libro";
}

<h2>Comando Select con join</h2>
<table class="table table-striped table-dark table-responsive-sm table-responsive-md">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codlibro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editorial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idioma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Codlibro)
            </td>
            <td>
                @Html.DisplayFor(model => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(model => item.Tema)
            </td>
            <td>
                @Html.DisplayFor(model => item.Editorial)
            </td>
            <td>
                @Html.DisplayFor(model => item.Idioma)
            </td>
            <td>
                @Html.DisplayFor(model => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(model => item.Year)
            </td>
        </tr>
    }
</table>

LINQ_Ejemplo/Views/Inicio/InsertarLibro.cshtml
@model LINQ_Ejemplo.Models.libros
@{
    ViewBag.Title = "Insertar Libro";
}
<h2>Comando Insert con procedimiento Almacenado</h2>

@using (Html.BeginForm("InsertarLibro", "Inicio", FormMethod.Post))
{
    if (ViewData["regresar"].ToString() != "index")
    {
        @Html.AntiForgeryToken()
        <form>
            <div class="form-group">
                Titulo:
                <p></p>
                @Html.TextBoxFor(model => model.titulo,new {@class="form-control"})
            </div>

            <div class="form-group">
                Tematica:
                <p></p>
                @Html.DropDownListFor(model => model.codtema, new SelectList(ViewBag.tema, "codtema", "tema"),new { @class = "form-control" })
            </div>
            <div class="form-group">
                Editorial:
                <p></p>
                @Html.DropDownListFor(model => model.codeditorial, new SelectList(ViewBag.edito, "codeditorial", "editorial"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                Idioma:
                <p></p>
                @Html.DropDownListFor(model => model.codidioma, new SelectList(ViewBag.idioma, "codidioma", "idioma"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                Autor:
                <p></p>
                @Html.DropDownListFor(model => model.codlibro, new SelectList(ViewBag.autor, "codautor", "autor"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                precio:
                <p></p>
                @Html.TextBoxFor(model => model.precio,new {@class="form-control"})
            </div>
            <div class="form-group">
                Año:
                <p></p>
                @Html.TextBoxFor(model => model.year, new { @class = "form-control" })
            </div>
            <div class="form-check">
                @Html.RadioButtonFor(model => model.donado, 1,new {@class="form-check-input",@checked="checked"})
                <label class="form-check-label">
                    Sí
                </label>
            </div>
            <div class="form-check">
                @Html.RadioButtonFor(model => model.donado, 0,new {@class="form-check-input"})
                <label class="form-check-label">
                    No
                </label>
            </div>
            <button type="submit" class="btn btn-primary" value="submit">Agregar</button>
        </form>
    }

    if (ViewData["regresar"].Equals("index"))
    {
          <div class="alert alert-success" role="alert">
              El libro se agregado con exito, Volver a @Html.ActionLink("Inicio", "Index", "Inicio", null)
          </div> 
      }
 }

LINQ_Ejemplo/Views/Inicio/ModificarAlumno.cshtml
@model LINQ_Ejemplo.Models.alumnos
@{
    ViewBag.Title = "Modificar Alumno";
}

<h2>Comando Update</h2>
@using (Html.BeginForm("ModificarAlumno", "Inicio", FormMethod.Post))
{
<div class="form-group">
    <label>Seleccione el alumno</label>
    @Html.DropDownListFor(model => model.codalumno, new SelectList(ViewBag.alumnos,"codalumno","nombre"), new  { @class = "form-control" })
</div>
    <div>
        <label for="nuevo">Ingrese el nuevo numero de telefono</label>
        <input id="nuevo" type="text" name="nuevo" data-mask="9999-9999" class="form-control" maxlength="9" onkeypress="return justNumbers(event)"/>
        <script type="text/javascript">
            function justNumbers(e) {
                var keynum = window.event ? window.event.keyCode : e.which;
                if ((keynum == 8 || keynum == 48))
                    return true;
                if (keynum <= 47 || keynum >= 58) return false;
                return /\d/.test(String.fromCharCode(keynum));
            }
        </script>
        <br/>
        <button type="submit" class="btn btn-primary" value="submit">Modificar telefono</button>
    </div>
}

LINQ_Ejemplo/Views/Inicio/VerAlumnos.cshtml
@model IEnumerable<LINQ_Ejemplo.Models.alumnos>
@{
    ViewBag.Title = "Ver Alumnos";
}

<h2>Select * from tabla</h2>

<table class="table table-striped table-dark table-responsive-sm table-responsive-md">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codalumno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th>
            Libros Prestados
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.codalumno)
            </td>
            <td>
                @Html.DisplayFor(model => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(model => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(model => item.numPrestados)
            </td>
        </tr>
    }
</table>

LINQ_Ejemplo/Views/Inicio/borrarAlumno.cshtml
@model LINQ_Ejemplo.Models.alumnos
@{
    ViewBag.Title = "Borrar Alumno";
}
<br />
<h2>Comando Delete</h2>

@using (Html.BeginForm("BorrarAlumno", "Inicio", FormMethod.Post))
{ 
<div class="form-group">
    @Html.DropDownListFor(model => model.codalumno, new SelectList(ViewBag.alumnos, "codalumno", "nombre"), new { @class = "form-control" })
</div>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#borrar">
        Borrar Alumno
    </button>
    <div class="modal fade" id="borrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Esta seguro que desea borrar el usuario?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Si borra este usuario ya no podra recuperar la informacion
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-danger" value="submit">Borrar</button>
                </div>
            </div>
        </div>
    </div>
}